#include <stdexcept>
#include <iostream>
/*
Code developed to help the use of try catch in handling errors in c++

*/
//Developer: Gabriel Cassino
//--------------------Treatment Exception with try catch on c++

using namespace std;
void switchop(int option){//procedure for switch case
    switch(option){
        case 1:
            cout << "\n1 Condition" << endl;//first procedure
            break;
        case 2:
            cout << "\n2 Condition" << endl;//second procedure
            break;
        case 3:
            cout << "\n3 Condition" << endl;//third procedure
            break;
        case 0://End of program
            cout << "\nThanks" << endl;
            cout<<"Finished Program"<<endl;
            exit(0);
    }

}
void GetValue(int c)//treatment exception and choice
{
    if (c>='a'&&c<='z'){//verify if c is letter
        throw invalid_argument("Please, only numbers. Try again.");
    //...
    }else{//....if number
        if (c>='0'&&c<='9'){//if number between 0 and 9
            cout<<"\n"<<"Option 0"<<c-48<<endl;//find number in ASCII and print on screen
            switchop(c-48);//send to procedure
        }else{//....if outside range
            cout<<"\n"<<"Option outside range"<<endl;
        }
    }
}
int main()
{
    do{//Loop for option's main

        try//start 
        {
            cout << "\n" ;
            cout << "Register" << endl;
            cout << "\nOptions\n" << endl;
            cout << "1 Option 1" << endl;
            cout << "2 Option 2" << endl;
            cout << "3 Option 3"<< endl;
            cout << "4 Option 4" << endl;
            cout << "5 Option 5" << endl;
            cout << "6 Option 6" << endl;
            cout << "\n0 Exit\n" << endl;
            cout<<"Insert a value:\n"<<endl;
            GetValue(getchar());//set value for analysis
        }
        catch (invalid_argument& e)//return exception
        {
            cerr <<"\n" << e.what() << endl;
        }
        //...
    }while(!getchar()==0);//end
    return 0;
}
